name: chorale_app
description: Application de gestion de partitions de chorale
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.8+4
  http: ^1.1.0
  path_provider: ^2.0.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_pdfview: ^1.2.3
  just_audio: ^0.9.41
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Les assets DOIVENT Ãªtre ici, sous flutter:
  assets:
    - assets/images/logo.png
    # Tu peux ajouter d'autres lignes si besoin, ex :
    # - assets/images/
    # - assets/icons/
    # - assets/sounds/